name: Deploy Node.js App to Azure

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build & Test Application
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint (Ignore Errors)
        run: npm run lint --if-present || true

      - name: Run Tests (Ignore Errors)
        run: npm run test --if-present || true

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Apply Prisma Migrations (Safe)
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          npx prisma migrate deploy || npx prisma db push

      - name: Build Application
        run: npm run build --if-present

      - name: Prepare Deployment Package
        run: |
          mkdir deploy-package
          rsync -av --progress ./ deploy-package --exclude deploy-package --exclude node_modules --exclude .git --exclude .github --exclude .next --exclude prisma/migrations
          zip -r release.zip deploy-package

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    name: Deploy to Azure Web App
    runs-on: ubuntu-latest
    needs: build
    environment: Production
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip Artifact
        run: unzip release.zip

      - name: List Files Before Deployment
        run: ls -la

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BA5784C1AC1847B48A936E704EFF6664 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BDCE9715CCD44C8E9CB267444F7CAE5E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_25E3289E5CC4419DAD89938A601F3AA5 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'mlaku-mulu-backend'
          slot-name: 'Production'
          package: release.zip
